"""
VIDEO QA PRE-PROCESSOR
======================
Extracts frames from screen recording videos and computes perceptual hashes.
Optimized for Intel Xeon E5-2676 v3 (12 cores / 24 threads) with 64GB RAM.

Arena crop is pixel-accurately calibrated for 1920x1040 video resolution.
Crop region verified by multi-patch pixel matching between full UI screenshot
and isolated arena screenshot. Mean pixel diff: 1.42 (near-perfect match).

Overlay masking (two layers):
  1. STATIC masks  -- known fixed regions blacked out with FFmpeg drawbox filters.
  2. MOVING logo   -- floating colorful logo detected per-frame with OpenCV and
                      removed via inpainting AFTER FFmpeg extraction.
This ensures that neither fixed nor drifting overlays pollute pHash comparisons
between the live video feed and recorded videos.

Requirements:
    pip install imagehash Pillow opencv-python numpy
    FFmpeg must be installed and added to system PATH

Usage (Windows):
    # Process all videos in a folder (arena-only, 1fps, overlays masked)
    python video_preprocess.py --input "D:\\video" --batch

    # Disable overlay masking (raw arena frames)
    python video_preprocess.py --input "D:\\video" --batch --no-mask

    # Disable moving logo removal only
    python video_preprocess.py --input "D:\\video" --batch --no-logo

    # Custom mask regions (replaces defaults, x:y:w:h in post-crop coords)
    python video_preprocess.py --input "D:\\video" --batch --mask 430:400:400:100 --mask 0:710:1260:62

    # Single video
    python video_preprocess.py --input "D:\\video\\recording1.mp4"

    # 2 frames per second (higher accuracy)
    python video_preprocess.py --input "D:\\video" --batch --fps 2

    # Scene-change mode (faster)
    python video_preprocess.py --input "D:\\video" --batch --mode scene

    # Custom output folder
    python video_preprocess.py --input "D:\\video" --batch --output "D:\\HashDB"

    # Override crop region manually (x:y:width:height)
    python video_preprocess.py --input "D:\\video" --batch --crop 11:71:1260:772

Author: Generated by Claude for QA video comparison pipeline
"""

import os
import re
import sys
import json
import time
import shutil
import argparse
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime, timedelta
from multiprocessing import Pool, cpu_count
from functools import partial

# ─────────────────────────────────────────────
# Windows: suppress console pop-up windows when
# spawning ffmpeg/ffprobe child processes
# ─────────────────────────────────────────────
_WIN = sys.platform == "win32"
_SUBPROCESS_KWARGS = {}
if _WIN:
    _SUBPROCESS_KWARGS["creationflags"] = subprocess.CREATE_NO_WINDOW


def _run(cmd, timeout=None):
    """
    Cross-platform subprocess.run wrapper.
    Always uses UTF-8 encoding with error replacement (safe on Windows).
    Suppresses console windows on Windows.
    """
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        **_SUBPROCESS_KWARGS,
    )


# ─────────────────────────────────────────────
# Dependency check (runs before any import)
# ─────────────────────────────────────────────
def check_dependencies():
    """Verify FFmpeg and required Python libraries are installed."""
    errors = []

    try:
        result = _run(["ffmpeg", "-version"], timeout=10)
        if result.returncode != 0:
            errors.append("FFmpeg is installed but returned an error.")
    except FileNotFoundError:
        errors.append(
            "FFmpeg not found.\n"
            "  1. Download from https://ffmpeg.org/download.html\n"
            "  2. Extract and add the bin\\ folder to Windows PATH\n"
            "  3. Restart your terminal"
        )
    except Exception as e:
        errors.append(f"FFmpeg check failed: {e}")

    try:
        import imagehash  # noqa: F401
    except ImportError:
        errors.append("imagehash not installed. Run: pip install imagehash")

    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        errors.append("Pillow not installed. Run: pip install Pillow")

    try:
        import cv2  # noqa: F401
    except ImportError:
        errors.append("opencv-python not installed. Run: pip install opencv-python")

    try:
        import numpy  # noqa: F401
    except ImportError:
        errors.append("numpy not installed. Run: pip install numpy")

    if errors:
        print("\n MISSING DEPENDENCIES:\n")
        for err in errors:
            print(f"  - {err}\n")
        print("Install all Python dependencies at once:")
        print("  pip install imagehash Pillow opencv-python numpy\n")
        sys.exit(1)
    else:
        print("All dependencies OK\n")


check_dependencies()

import imagehash          # noqa: E402  (must be after dependency check)
from PIL import Image     # noqa: E402
import cv2                # noqa: E402
import numpy as np        # noqa: E402


# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────
HASH_ALGORITHM   = "phash"
HASH_SIZE        = 16          # 16x16 = 256-bit hash (high accuracy)
VIDEO_EXTENSIONS = {".mp4", ".mkv", ".avi", ".mov", ".webm", ".flv", ".wmv"}

CONFIG = {
    "num_cores": cpu_count()
}

# ─────────────────────────────────────────────
# Arena crop -- pixel-accurate for 1920x1040
# ─────────────────────────────────────────────
# HOW THIS WAS CALCULATED:
#   Full UI screenshot  : 1222 x 612 px
#   Arena screenshot    : 802  x 454 px
#   Multi-patch pixel matching found arena offset: x=7, y=42 in full screenshot
#   Scale X = 1920 / 1222 = 1.57119476
#   Scale Y = 1040 / 612  = 1.69934641
#   crop_x  = round(7   * 1.57119) = 11
#   crop_y  = round(42  * 1.69935) = 71
#   crop_w  = round(802 * 1.57119) = 1260
#   crop_h  = round(454 * 1.69935) = 772
#   Boundary check: (11+1260)=1271 <= 1920 OK  |  (71+772)=843 <= 1040 OK
#   Pixel match verification: mean pixel diff = 1.42 (near-perfect match)
#   Coverage: 65.6% of width x 74.2% of height = 48.7% of total frame
#
# Excludes:
#   - Top bar  (Fight No#, logo)
#   - Right panel (MERON / TIE / WALA betting odds)
#   - Bottom icon row
#   - Bottom number/betting history circles
# ─────────────────────────────────────────────
ARENA_CROP = {
    "x":      11,    # pixels from left edge
    "y":      71,    # pixels from top edge
    "width":  1260,  # arena width  in real video pixels
    "height": 772,   # arena height in real video pixels
}

# ─────────────────────────────────────────────
# Overlay masks -- black out regions AFTER crop
# ─────────────────────────────────────────────
# Coordinates are relative to the CROPPED arena (1260x772).
# These regions contain changing overlays (watermarks, timestamps,
# logos, icons) that would pollute pHash comparisons.
#
# HOW TO CALIBRATE:
#   1. Run the script once WITHOUT masks (--no-mask)
#   2. Open any extracted frame in an image editor
#   3. Note the x, y, width, height of each overlay zone
#   4. Update these values or use --mask on the CLI
#
# Each mask: {"x": left, "y": top, "w": width, "h": height}
# ─────────────────────────────────────────────
OVERLAY_MASKS = [
    # Center watermark + timestamp (SABONG24 logo icon + "SABONG24" text + date/time)
    # Verified from 1252x908 browser screenshot of 1920x1040 video stream
    # Covers the logo, text, and full timestamp with padding
    {"x": 400, "y": 346, "w": 495, "h": 125, "label": "watermark+timestamp"},

    # Bottom-right circular logo (small icon at lower-right corner of arena)
    {"x": 1178, "y": 691, "w": 82, "h": 81, "label": "bottom_right_logo"},
]


# ─────────────────────────────────────────────
# Moving logo detector + remover
# ─────────────────────────────────────────────
# Detects a floating colorful logo that drifts around the frame
# (independent of the static drawbox masks above).
# Works on already-extracted JPEG frames (post-FFmpeg).
#
# Strategy:
#   1. Saturation mask  -- logo is thick and colorful (high HSV saturation)
#   2. Motion mask      -- logo moves independently from video content
#   3. Intersection     -- colorful AND moving = floating logo
#   4. Position history -- smooths detection across frames (logo moves slowly)
#   5. Inpainting       -- fills detected region with surrounding pixels
#
# All coordinates are relative to the CROPPED arena frame (1260x772).
# ─────────────────────────────────────────────

# Tuning knobs -- adjust if logo is not detected correctly
MOVING_LOGO_CONFIG = {
    "min_area":        500,    # ignore blobs smaller than this (px²)
    "max_area_ratio":  0.08,   # logo won't exceed 8% of frame area
    "sat_threshold":   80,     # HSV saturation threshold (0-255)
    "motion_threshold": 15,    # pixel diff threshold for motion mask
    "inpaint_radius":  5,      # inpainting brush radius (px)
    "history_size":    15,     # frames to remember for position smoothing
    "pad":             10,     # extra padding around detected bbox (px)
}


class MovingLogoDetector:
    """
    Per-video stateful detector for a floating colorful logo.
    Create one instance per video; call detect(frame) on each frame in order.
    """

    def __init__(self, cfg=None):
        c = cfg or MOVING_LOGO_CONFIG
        self.min_area       = c["min_area"]
        self.max_area_ratio = c["max_area_ratio"]
        self.sat_thresh     = c["sat_threshold"]
        self.motion_thresh  = c["motion_threshold"]
        self.history_size   = c["history_size"]
        self.pad            = c["pad"]
        self.prev_gray      = None
        self.history        = []   # recent (x, y, w, h) detections

    def detect(self, frame):
        """
        Returns (x, y, w, h) bounding box of the floating logo, or None.
        frame: BGR numpy array (already-cropped arena frame).
        """
        h, w = frame.shape[:2]
        max_area = w * h * self.max_area_ratio

        # ── Saturation mask: logo is thick + colorful ──
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        _, sat_mask = cv2.threshold(
            hsv[:, :, 1], self.sat_thresh, 255, cv2.THRESH_BINARY)

        # ── Motion mask: logo moves independently ──
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        if self.prev_gray is None:
            self.prev_gray = gray
            return None

        diff = cv2.absdiff(gray, self.prev_gray)
        self.prev_gray = gray.copy()
        _, motion_mask = cv2.threshold(
            diff, self.motion_thresh, 255, cv2.THRESH_BINARY)

        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
        motion_mask = cv2.dilate(motion_mask, kernel, iterations=2)

        # ── Combine: must be colorful AND moving ──
        combined = cv2.bitwise_and(sat_mask, motion_mask)
        combined = cv2.morphologyEx(combined, cv2.MORPH_OPEN,
                                    np.ones((5, 5), np.uint8))
        combined = cv2.morphologyEx(combined, cv2.MORPH_CLOSE,
                                    np.ones((20, 20), np.uint8))

        # ── Find best contour ──
        contours, _ = cv2.findContours(
            combined, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        best, best_score = None, 0
        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area < self.min_area or area > max_area:
                continue
            bx, by, bw, bh = cv2.boundingRect(cnt)
            score = area
            # Prefer regions near historical logo position (logo drifts slowly)
            if self.history:
                avg_x = np.mean([r[0] for r in self.history])
                avg_y = np.mean([r[1] for r in self.history])
                dist  = np.hypot(bx - avg_x, by - avg_y)
                score += max(0, 5000 - dist * 10)
            if score > best_score:
                best_score = score
                best = (bx, by, bw, bh)

        if best:
            bx, by, bw, bh = best
            # Add padding, clamp to frame bounds
            bx = max(0, bx - self.pad)
            by = max(0, by - self.pad)
            bw = min(w - bx, bw + self.pad * 2)
            bh = min(h - by, bh + self.pad * 2)
            best = (bx, by, bw, bh)
            self.history.append(best)
            if len(self.history) > self.history_size:
                self.history.pop(0)

        return best


def remove_moving_logo(frame, bbox):
    """
    Inpaint (remove) the detected logo region from a frame.
    bbox: (x, y, w, h) or None.
    Returns the cleaned frame (or original if bbox is None).
    """
    if bbox is None:
        return frame
    x, y, w, h = bbox
    mask = np.zeros(frame.shape[:2], dtype=np.uint8)
    mask[y:y + h, x:x + w] = 255
    return cv2.inpaint(
        frame, mask,
        inpaintRadius=MOVING_LOGO_CONFIG["inpaint_radius"],
        flags=cv2.INPAINT_TELEA,
    )


def apply_moving_logo_removal(frame_data, remove_logo=True):
    """
    Post-process all extracted JPEG frames in frame_data:
      - Open each frame with OpenCV
      - Detect floating logo (stateful, sequential)
      - Inpaint logo region
      - Overwrite the JPEG in-place

    frame_data: list of {"path": str, "timestamp": float}
    remove_logo: set False to skip (pass-through)
    Returns counts: (cleaned, skipped, errors)
    """
    if not remove_logo or not frame_data:
        return 0, len(frame_data), 0

    detector = MovingLogoDetector()
    cleaned = skipped = errors = 0

    for fd in frame_data:
        try:
            frame = cv2.imread(fd["path"])
            if frame is None:
                errors += 1
                continue
            bbox         = detector.detect(frame)
            clean_frame  = remove_moving_logo(frame, bbox)
            cv2.imwrite(fd["path"], clean_frame,
                        [cv2.IMWRITE_JPEG_QUALITY, 95])
            if bbox:
                cleaned += 1
            else:
                skipped += 1
        except Exception as e:
            print("  WARNING: moving logo removal failed for {}: {}".format(
                fd["path"], e))
            errors += 1

    return cleaned, skipped, errors


def build_vf(extra, crop, masks=None):
    """
    Build FFmpeg -vf filter chain:
      1. Crop to arena region
      2. Draw black boxes over overlay zones (masks)
      3. Apply any extra filter (fps, scene detect, etc.)
    FFmpeg crop syntax:  crop=w:h:x:y
    FFmpeg drawbox syntax: drawbox=x:y:w:h:color=black:t=fill
    """
    c = crop
    filters = []

    # Step 1: crop to arena
    filters.append("crop={}:{}:{}:{}".format(c["width"], c["height"], c["x"], c["y"]))

    # Step 2: mask overlays with black boxes
    if masks:
        for m in masks:
            filters.append("drawbox=x={}:y={}:w={}:h={}:color=black:t=fill".format(
                m["x"], m["y"], m["w"], m["h"]
            ))

    # Step 3: extra filters (fps, scene, etc.)
    if extra:
        filters.append(extra)

    return ",".join(filters)


# ─────────────────────────────────────────────
# Utility
# ─────────────────────────────────────────────
def format_duration(seconds):
    return str(timedelta(seconds=int(seconds)))


def get_video_duration(video_path):
    try:
        r = _run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_format", str(video_path)],
            timeout=30,
        )
        return float(json.loads(r.stdout)["format"]["duration"])
    except Exception as e:
        print("  WARNING: Could not get duration: {}".format(e))
        return None


def _safe_fps(rate_str):
    """Parse ffprobe r_frame_rate (e.g. '30/1', '24000/1001') without eval()."""
    try:
        if "/" in rate_str:
            num, den = rate_str.split("/")
            return float(num) / float(den)
        return float(rate_str)
    except Exception:
        return 30.0


def get_video_info(video_path):
    try:
        r = _run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_streams", "-select_streams", "v:0", str(video_path)],
            timeout=30,
        )
        s = json.loads(r.stdout)["streams"][0]
        return {
            "width":  s.get("width"),
            "height": s.get("height"),
            "codec":  s.get("codec_name"),
            "fps":    _safe_fps(s.get("r_frame_rate", "30/1")),
        }
    except Exception:
        return {}


# ─────────────────────────────────────────────
# Frame extraction
# ─────────────────────────────────────────────
def extract_frames_fps(video_path, output_dir, fps=1, crop=None, masks=None):
    """Extract frames at fixed rate, cropped to arena region only, overlays masked."""
    c = crop or ARENA_CROP
    print("  Extracting at {} fps | arena {}x{} @ x={}, y={}...".format(
        fps, c["width"], c["height"], c["x"], c["y"]))

    out_pattern = str(Path(output_dir) / "frame_%06d.jpg")
    cmd = [
        "ffmpeg", "-i", str(video_path),
        "-vf", build_vf("fps={}".format(fps), c, masks),
        "-q:v", "2",
        "-frame_pts", "1",
        out_pattern,
    ]
    result = _run(cmd)
    if result.returncode != 0:
        print("  ERROR - FFmpeg:\n{}".format(result.stderr[-600:]))
        return []

    frames = sorted(Path(output_dir).glob("frame_*.jpg"))
    frame_data = [
        {"path": str(f), "timestamp": round(i / fps, 2)}
        for i, f in enumerate(frames)
    ]
    print("  Extracted {} frames".format(len(frame_data)))
    return frame_data


def extract_frames_scene(video_path, output_dir, threshold=0.3, crop=None, masks=None):
    """Extract frames on scene change within arena region."""
    c = crop or ARENA_CROP
    print("  Scene-change extraction (threshold={}) | arena {}x{} @ x={}, y={}...".format(
        threshold, c["width"], c["height"], c["x"], c["y"]))

    out_pattern = str(Path(output_dir) / "scene_%06d.jpg")
    vf = build_vf("select='gt(scene\\,{})',showinfo".format(threshold), c, masks)
    cmd = [
        "ffmpeg", "-i", str(video_path),
        "-vf", vf,
        "-vsync", "vfr",
        "-q:v", "2",
        out_pattern,
    ]
    result = _run(cmd)
    if result.returncode != 0:
        print("  ERROR - FFmpeg:\n{}".format(result.stderr[-600:]))
        return []

    frames = sorted(Path(output_dir).glob("scene_*.jpg"))
    timestamps = re.findall(r"pts_time:(\d+\.?\d*)", result.stderr)

    frame_data = [
        {"path": str(f),
         "timestamp": round(float(timestamps[i]) if i < len(timestamps) else i * 4.0, 2)}
        for i, f in enumerate(frames)
    ]
    print("  Extracted {} scene-change frames".format(len(frame_data)))
    return frame_data


def extract_frames_keyframe(video_path, output_dir, crop=None, masks=None):
    """Extract only I-frames (keyframes), cropped to arena."""
    c = crop or ARENA_CROP
    print("  Keyframe extraction | arena {}x{} @ x={}, y={}...".format(
        c["width"], c["height"], c["x"], c["y"]))

    out_pattern = str(Path(output_dir) / "key_%06d.jpg")
    vf = build_vf("select='eq(pict_type\\,I)',showinfo", c, masks)
    cmd = [
        "ffmpeg", "-i", str(video_path),
        "-vf", vf,
        "-vsync", "vfr",
        "-q:v", "2",
        out_pattern,
    ]
    result = _run(cmd)

    frames = sorted(Path(output_dir).glob("key_*.jpg"))
    timestamps = re.findall(r"pts_time:(\d+\.?\d*)", result.stderr)

    frame_data = [
        {"path": str(f),
         "timestamp": round(float(timestamps[i]) if i < len(timestamps) else i * 2.5, 2)}
        for i, f in enumerate(frames)
    ]
    print("  Extracted {} keyframes".format(len(frame_data)))
    return frame_data


def extract_frames_twopass(video_path, output_dir, gap_threshold=10, crop=None, masks=None):
    """
    Two-pass: keyframes first, then fill gaps > gap_threshold seconds.
    Best speed/coverage balance. All frames cropped to arena.
    """
    c = crop or ARENA_CROP
    print("  Two-pass extraction (gap threshold: {}s)...".format(gap_threshold))

    print("      Pass 1: Keyframes...")
    keyframe_data = extract_frames_keyframe(video_path, output_dir, crop=c, masks=masks)

    if not keyframe_data:
        print("      WARNING: No keyframes found, falling back to 1fps")
        return extract_frames_fps(video_path, output_dir, fps=1, crop=c, masks=masks)

    print("      Pass 2: Filling gaps > {}s...".format(gap_threshold))
    gaps = []
    for i in range(1, len(keyframe_data)):
        gap = keyframe_data[i]["timestamp"] - keyframe_data[i - 1]["timestamp"]
        if gap > gap_threshold:
            gaps.append((keyframe_data[i - 1]["timestamp"] + keyframe_data[i]["timestamp"]) / 2)

    gap_frames = []
    if gaps:
        gap_dir = Path(output_dir) / "gaps"
        gap_dir.mkdir(exist_ok=True)

        for idx, gap_time in enumerate(gaps):
            out_file = str(gap_dir / "gap_{:06d}.jpg".format(idx))
            vf = build_vf("", c, masks)
            cmd = [
                "ffmpeg",
                "-ss", str(gap_time),
                "-i", str(video_path),
                "-vf", vf,
                "-frames:v", "1",
                "-q:v", "2",
                out_file,
            ]
            _run(cmd)
            if os.path.exists(out_file):
                gap_frames.append({"path": out_file, "timestamp": round(gap_time, 2)})

    all_frames = sorted(keyframe_data + gap_frames, key=lambda x: x["timestamp"])
    print("      {} keyframes + {} gap-fills = {} total frames".format(
        len(keyframe_data), len(gap_frames), len(all_frames)))
    return all_frames


# ─────────────────────────────────────────────
# Perceptual hashing (parallelized)
# ─────────────────────────────────────────────
def _hash_one_frame(frame_info, hash_size=HASH_SIZE):
    """Compute pHash for a single frame. Runs inside a worker process."""
    try:
        img = Image.open(frame_info["path"])
        h = imagehash.phash(img, hash_size=hash_size)
        return {"t": frame_info["timestamp"], "h": str(h)}
    except Exception as e:
        return {"t": frame_info["timestamp"], "h": None, "error": str(e)}


def compute_hashes_parallel(frame_data, num_workers=None):
    num_workers = num_workers or CONFIG["num_cores"]
    print("  Computing p-hashes using {} cores...".format(num_workers))
    start = time.time()

    hash_func = partial(_hash_one_frame, hash_size=HASH_SIZE)
    with Pool(processes=num_workers) as pool:
        results = pool.map(hash_func, frame_data)

    valid  = [r for r in results if r.get("h") is not None]
    errors = [r for r in results if r.get("h") is None]

    elapsed = time.time() - start
    rate = len(valid) / elapsed if elapsed > 0 else 0
    print("  Hashed {} frames in {:.1f}s ({:.0f} frames/sec)".format(len(valid), elapsed, rate))
    if errors:
        print("  WARNING: {} frames failed to hash".format(len(errors)))

    return valid


# ─────────────────────────────────────────────
# Main pipeline
# ─────────────────────────────────────────────
def process_video(video_path, output_dir, mode="fps", fps=1, scene_threshold=0.3, crop=None, masks=None, no_logo=False):
    """Full pipeline: crop arena -> mask overlays -> extract frames -> p-hash -> save JSON."""
    c = crop or ARENA_CROP
    m = masks  # None means no masking (--no-mask), list means apply masks
    video_path = Path(video_path)
    video_name = video_path.name

    # ── Checkpoint: skip if already processed ──
    # JSON is written only after full successful completion,
    # so its existence guarantees the video was fully processed.
    os.makedirs(output_dir, exist_ok=True)
    json_path = str(Path(output_dir) / (video_path.stem + "_hashes.json"))
    if os.path.exists(json_path):
        size_mb = os.path.getsize(json_path) / (1024 * 1024)
        print("\n" + "=" * 60)
        print("  SKIPPING: {} (already processed)".format(video_name))
        print("  Found:    {} ({:.2f} MB)".format(json_path, size_mb))
        print("=" * 60)
        return json_path

    print("\n" + "=" * 60)
    print("  Processing: {}".format(video_name))
    print("=" * 60)
    print("  Arena crop:  x={}, y={}, width={}, height={} (1920x1040 pixels)".format(
        c["x"], c["y"], c["width"], c["height"]))
    if m:
        print("  Overlay masks: {} regions masked out".format(len(m)))
        for mask in m:
            print("    - {}: x={}, y={}, {}x{} px".format(
                mask.get("label", "unnamed"), mask["x"], mask["y"], mask["w"], mask["h"]))
    else:
        print("  Overlay masks: DISABLED (raw arena frames)")

    duration = get_video_duration(video_path)
    info     = get_video_info(video_path)

    if duration:
        print("  Duration:    {}".format(format_duration(duration)))
    if info:
        print("  Resolution:  {}x{}".format(info.get("width"), info.get("height")))
        print("  Codec:       {}".format(info.get("codec")))

    temp_dir = tempfile.mkdtemp(prefix="vqa_")
    print("  Temp dir:    {}".format(temp_dir))
    overall_start = time.time()

    try:
        extract_start = time.time()

        if mode == "fps":
            frame_data = extract_frames_fps(video_path, temp_dir, fps=fps, crop=c, masks=m)
        elif mode == "scene":
            frame_data = extract_frames_scene(video_path, temp_dir, threshold=scene_threshold, crop=c, masks=m)
        elif mode == "keyframe":
            frame_data = extract_frames_keyframe(video_path, temp_dir, crop=c, masks=m)
        elif mode == "twopass":
            frame_data = extract_frames_twopass(video_path, temp_dir, crop=c, masks=m)
        else:
            print("  ERROR: Unknown mode: {}".format(mode))
            return None

        extract_time = time.time() - extract_start
        print("  Extraction time: {:.1f}s".format(extract_time))

        if not frame_data:
            print("  ERROR: No frames extracted!")
            return None

        # ── Moving logo removal (post-FFmpeg, per-frame OpenCV inpainting) ──
        if not no_logo:
            print("  Detecting and removing floating logo...")
            cleaned, skipped, logo_errors = apply_moving_logo_removal(
                frame_data, remove_logo=True)
            print("  Moving logo: {} frames cleaned | {} no logo | {} errors".format(
                cleaned, skipped, logo_errors))
        else:
            print("  Moving logo removal: DISABLED (--no-logo)")

        hash_start   = time.time()
        hash_results = compute_hashes_parallel(frame_data)
        hash_time    = time.time() - hash_start

        output_data = {
            "video_name":       video_name,
            "video_path":       str(video_path),
            "duration_seconds": duration,
            "duration_human":   format_duration(duration) if duration else None,
            "resolution":       "{}x{}".format(info.get("width"), info.get("height")) if info else None,
            "arena_crop": {
                "x":      c["x"],
                "y":      c["y"],
                "width":  c["width"],
                "height": c["height"],
                "note":   "Pixel-accurate for 1920x1040. Excludes top bar, right betting panel, bottom UI.",
            },
            "overlay_masks": [
                {"x": mask["x"], "y": mask["y"], "w": mask["w"], "h": mask["h"],
                 "label": mask.get("label", "")}
                for mask in m
            ] if m else None,
            "moving_logo_removal": not no_logo,
            "hash_algorithm":   HASH_ALGORITHM,
            "hash_size":        HASH_SIZE,
            "extraction_mode":  mode,
            "extraction_fps":   fps if mode == "fps" else None,
            "total_frames":     len(hash_results),
            "processed_at":     datetime.now().isoformat(),
            "processing_time": {
                "extraction_seconds": round(extract_time, 1),
                "hashing_seconds":    round(hash_time, 1),
                "total_seconds":      round(time.time() - overall_start, 1),
            },
            "cores_used": CONFIG["num_cores"],
            "frames":     hash_results,
        }

        os.makedirs(output_dir, exist_ok=True)
        json_path = str(Path(output_dir) / (video_path.stem + "_hashes.json"))

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(output_data, f, indent=2, ensure_ascii=False)

        file_size  = os.path.getsize(json_path) / (1024 * 1024)
        total_time = time.time() - overall_start

        print("\n  " + "-" * 36)
        print("  RESULTS for {}".format(video_name))
        print("  " + "-" * 36)
        print("  Frames hashed:     {}".format(len(hash_results)))
        print("  JSON file:         {}".format(json_path))
        print("  JSON size:         {:.2f} MB".format(file_size))
        print("  Extraction time:   {:.1f}s".format(extract_time))
        print("  Hashing time:      {:.1f}s".format(hash_time))
        print("  Total time:        {}".format(format_duration(total_time)))
        print("  " + "-" * 36)

        return json_path

    finally:
        print("  Cleaning up temp files...")
        shutil.rmtree(temp_dir, ignore_errors=True)


def process_batch(input_dir, output_dir, mode="fps", fps=1, crop=None, masks=None, no_logo=False):
    """Process all video files in a directory."""
    c = crop or ARENA_CROP
    input_dir   = Path(input_dir)
    video_files = []

    for ext in VIDEO_EXTENSIONS:
        video_files.extend(input_dir.glob("*{}".format(ext)))
        video_files.extend(input_dir.glob("*{}".format(ext.upper())))

    video_files = sorted(set(video_files))

    if not video_files:
        print("ERROR: No video files found in {}".format(input_dir))
        print("   Supported formats: {}".format(", ".join(VIDEO_EXTENSIONS)))
        return

    print("\n" + "#" * 60)
    print("  BATCH PROCESSING: {} videos".format(len(video_files)))
    print("  Mode:   {} | Cores: {}".format(mode, CONFIG["num_cores"]))
    print("  Arena:  x={}, y={}, {}x{} px".format(c["x"], c["y"], c["width"], c["height"]))
    if masks:
        print("  Masks:  {} overlay regions will be blacked out".format(len(masks)))
    else:
        print("  Masks:  DISABLED (raw arena frames)")
    print("  Resume: already-processed videos will be skipped instantly")
    print("#" * 60)

    batch_start = time.time()
    results  = []
    skipped  = []
    failed   = []

    for i, video_file in enumerate(video_files, 1):
        print("\n  [{}/{}]".format(i, len(video_files)))

        # Track whether this was a skip or fresh process
        json_check = str(Path(output_dir) / (video_file.stem + "_hashes.json"))
        was_already_done = os.path.exists(json_check)

        json_path = process_video(video_file, output_dir, mode=mode, fps=fps, crop=c, masks=masks, no_logo=no_logo)

        if json_path and was_already_done:
            skipped.append(json_path)
        elif json_path:
            results.append(json_path)
        else:
            failed.append(str(video_file))

    batch_time = time.time() - batch_start

    print("\n\n" + "#" * 60)
    print("  BATCH COMPLETE")
    print("#" * 60)
    print("  Total videos:      {}".format(len(video_files)))
    print("  Newly processed:   {}".format(len(results)))
    print("  Skipped (done):    {}".format(len(skipped)))
    print("  Failed:            {}".format(len(failed)))
    print("  Total time:        {}".format(format_duration(batch_time)))
    print("  Output directory:  {}".format(output_dir))
    if results:
        print("\n  Newly created JSON files:")
        for r in results:
            size = os.path.getsize(r) / (1024 * 1024)
            print("    - {} ({:.2f} MB)".format(os.path.basename(r), size))
    if failed:
        print("\n  FAILED videos (rerun script to retry):")
        for f in failed:
            print("    - {}".format(os.path.basename(f)))
    print("#" * 60 + "\n")


# ─────────────────────────────────────────────
# System Architecture
# ─────────────────────────────────────────────
def print_architecture():
    """Print the full system architecture diagram to the console."""
    arch = r"""
================================================================================
                    VIDEO QA PRE-PROCESSOR — SYSTEM ARCHITECTURE
================================================================================

    ┌──────────────────────────────────────────────────────────────────────┐
    │                        CLI ENTRY (argparse)                         │
    │          --input  --batch  --mode  --fps  --crop  --mask            │
    │          --no-mask  --no-logo  --output  --cores                    │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼
    ┌──────────────────────────────────────────────────────────────────────┐
    │                      DEPENDENCY CHECKER                             │
    │         FFmpeg (PATH)  │  imagehash  │  Pillow  │  OpenCV  │  numpy │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼
    ┌──────────────────────────────────────────────────────────────────────┐
    │                       PROCESSING ROUTER                             │
    │              Single file  ──or──  Batch directory                   │
    └─────────┬────────────────────────────────────┬──────────────────────┘
              │                                    │
              ▼                                    ▼
    ┌───────────────────┐              ┌────────────────────────┐
    │  process_video()  │◄─────────────│    process_batch()     │
    │  (single file)    │  iterates    │  (all videos in dir)   │
    └────────┬──────────┘  per video   └────────────────────────┘
             │
             ▼
    ┌──────────────────────────────────────────────────────────────────────┐
    │                     CHECKPOINT / RESUME                             │
    │           Skip if _hashes.json already exists for video             │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼
    ┌──────────────────────────────────────────────────────────────────────┐
    │                    VIDEO PROBE (ffprobe)                            │
    │         Duration  │  Resolution  │  Codec  │  Native FPS            │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼
    ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─┐
    │           FRAME EXTRACTION (FFmpeg, 4 modes available)             │
    │                                                                     │
    │  ┌──────────┐  ┌───────────┐  ┌───────────┐  ┌──────────────────┐  │
    │  │   FPS    │  │   Scene   │  │ Keyframe  │  │    Two-pass      │  │
    │  │ (fixed   │  │ (change   │  │ (I-frames │  │ (keys + gap-fill │  │
    │  │  rate)   │  │  detect)  │  │   only)   │  │  for coverage)   │  │
    │  └──────────┘  └───────────┘  └───────────┘  └──────────────────┘  │
    └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┬ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─┘
                                  │
                                  ▼
    ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─┐
    │              FFmpeg -vf FILTER CHAIN (build_vf)                     │
    │                                                                     │
    │  ┌─────────────┐     ┌──────────────────┐     ┌──────────────┐     │
    │  │ Arena crop   │────►│ Static drawbox   │────►│ Rate filter  │     │
    │  │ 1260x772     │     │ (overlay masks)  │     │ (fps/scene)  │     │
    │  │ @x=11,y=71   │     │ watermark+logo   │     │              │     │
    │  └─────────────┘     └──────────────────┘     └──────────────┘     │
    └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┬ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─┘
                                  │
                                  ▼  (extracted JPEG frames on disk)
    ┌──────────────────────────────────────────────────────────────────────┐
    │              MOVING LOGO DETECTOR (OpenCV, per-frame)              │
    │                                                                     │
    │  ┌──────────────┐   ┌──────────────┐   ┌───────────┐              │
    │  │ Saturation   │   │   Motion     │   │ Intersect │   Inpaint    │
    │  │ mask (HSV    │──►│ mask (frame  │──►│ colorful  │──►(TELEA)    │
    │  │ S > thresh)  │   │ diff > 15)   │   │ + moving  │              │
    │  └──────────────┘   └──────────────┘   └───────────┘              │
    │                                                                     │
    │  Position history: smooths across 15 frames (logo drifts slowly)   │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼  (cleaned frames)
    ┌──────────────────────────────────────────────────────────────────────┐
    │             PARALLEL pHASH (multiprocessing.Pool)                   │
    │                                                                     │
    │  imagehash.phash()  │  hash_size=16  │  256-bit per frame           │
    │  Workers = cpu_count()  │  Parallel map over all frames             │
    └──────────────────────────┬───────────────────────────────────────────┘
                               │
                               ▼
    ┌──────────────────────────────────────────────────────────────────────┐
    │                      JSON OUTPUT                                    │
    │                                                                     │
    │  <video_name>_hashes.json                                           │
    │  ├── video metadata (name, path, duration, resolution, codec)       │
    │  ├── arena_crop config (x, y, width, height)                        │
    │  ├── overlay_masks config (regions masked)                          │
    │  ├── processing_time (extraction + hashing + total)                 │
    │  └── frames[] ── [{t: timestamp, h: "hex_hash"}, ...]              │
    └──────────────────────────────────────────────────────────────────────┘

================================================================================
  Key modules & classes:
    • MovingLogoDetector  — stateful per-video floating logo tracker
    • build_vf()          — constructs FFmpeg filter chain string
    • _hash_one_frame()   — single-frame pHash (runs in worker process)
    • process_video()     — full pipeline for one video file
    • process_batch()     — iterates process_video() over a directory

  Data flow:
    Video file ──► FFmpeg (crop + mask + extract) ──► JPEG frames
    JPEG frames ──► OpenCV (detect + inpaint logo) ──► cleaned frames
    Cleaned frames ──► imagehash (parallel pHash) ──► JSON hash database
================================================================================
"""
    print(arch)


# ─────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Video QA Pre-Processor: Extract arena frames and compute perceptual hashes",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=r"""
Examples (Windows):
  # All videos in folder, 1fps (default, with overlay masking)
  python video_preprocess.py --input "D:\video" --batch

  # Disable overlay masking (raw arena frames)
  python video_preprocess.py --input "D:\video" --batch --no-mask

  # Add extra mask region (x:y:w:h)
  python video_preprocess.py --input "D:\video" --batch --mask 430:400:400:100

  # All videos, 2fps (higher accuracy)
  python video_preprocess.py --input "D:\video" --batch --fps 2

  # Scene-change mode (faster)
  python video_preprocess.py --input "D:\video" --batch --mode scene

  # Single video
  python video_preprocess.py --input "D:\video\recording1.mp4"

  # Custom output folder
  python video_preprocess.py --input "D:\video" --batch --output "D:\HashDB"

  # Override crop only if your video resolution is different from 1920x1040
  python video_preprocess.py --input "D:\video" --batch --crop 11:71:1260:772

  # Show system architecture diagram
  python video_preprocess.py --architecture
        """
    )

    parser.add_argument("--architecture", "-a", action="store_true",
                        help="Print the full system architecture diagram and exit")
    parser.add_argument("--input",  "-i", required=False, default=None,
                        help="Path to a video file or directory (use with --batch)")
    parser.add_argument("--output", "-o", default=None,
                        help="Output directory for JSON files (default: <input>\\hash_db)")
    parser.add_argument("--batch",  "-b", action="store_true",
                        help="Process all videos in the input directory")
    parser.add_argument("--mode",   "-m",
                        choices=["fps", "scene", "keyframe", "twopass"], default="fps",
                        help="Frame extraction mode (default: fps)")
    parser.add_argument("--fps",    "-f", type=float, default=1.0,
                        help="Frames per second for fps mode (default: 1)")
    parser.add_argument("--cores",  "-c", type=int, default=None,
                        help="CPU cores to use (default: auto = {})".format(CONFIG["num_cores"]))
    parser.add_argument("--crop", type=str, default=None,
                        help="Override arena crop as x:y:width:height "
                             "(default: 11:71:1260:772 for 1920x1040 video)")
    parser.add_argument("--no-mask", action="store_true",
                        help="Disable overlay masking (use raw arena frames without drawbox)")
    parser.add_argument("--no-logo", action="store_true",
                        help="Disable moving logo detection and inpainting")
    parser.add_argument("--mask", type=str, action="append", default=None,
                        help="Add/override mask region as x:y:w:h (can be used multiple times). "
                             "When used, REPLACES the built-in masks. "
                             "Coordinates are relative to the CROPPED arena.")

    args = parser.parse_args()

    # ── Show architecture and exit ──
    if args.architecture:
        print_architecture()
        sys.exit(0)

    # ── Require --input for actual processing ──
    if args.input is None:
        parser.error("--input is required (unless using --architecture)")

    # Apply core override
    if args.cores:
        CONFIG["num_cores"] = min(args.cores, cpu_count())

    # Parse crop override
    crop = None
    if args.crop:
        try:
            x, y, w, h = map(int, args.crop.split(":"))
            crop = {"x": x, "y": y, "width": w, "height": h}
        except Exception:
            print("ERROR: Invalid --crop. Use format x:y:width:height  e.g.  11:71:1260:772")
            sys.exit(1)

    # Resolve overlay masks
    if args.no_mask:
        masks = None
    elif args.mask:
        # User-specified masks replace built-in defaults
        masks = []
        for i, m_str in enumerate(args.mask):
            try:
                mx, my, mw, mh = map(int, m_str.split(":"))
                masks.append({"x": mx, "y": my, "w": mw, "h": mh, "label": "custom_{}".format(i + 1)})
            except Exception:
                print("ERROR: Invalid --mask '{}'. Use format x:y:w:h  e.g.  430:400:400:100".format(m_str))
                sys.exit(1)
    else:
        # Default: use built-in OVERLAY_MASKS
        masks = OVERLAY_MASKS

    # Default output directory
    if args.output is None:
        base = args.input if args.batch else str(Path(args.input).parent)
        args.output = str(Path(base) / "hash_db")

    c = crop or ARENA_CROP
    print("\nVIDEO QA PRE-PROCESSOR")
    print("   Input:       {}".format(args.input))
    print("   Output:      {}".format(args.output))
    print("   Mode:        {}".format(args.mode))
    print("   Cores:       {}".format(CONFIG["num_cores"]))
    print("   Arena crop:  x={}, y={}, {}x{} px (calibrated for 1920x1040)".format(
        c["x"], c["y"], c["width"], c["height"]))
    if masks:
        print("   Masks:       {} overlay regions".format(len(masks)))
        for mask in masks:
            print("                - {}: x={}, y={}, {}x{} px".format(
                mask.get("label", "unnamed"), mask["x"], mask["y"], mask["w"], mask["h"]))
    else:
        print("   Masks:       DISABLED")
    print("   Moving logo: {}".format("DISABLED (--no-logo)" if args.no_logo else "detection + inpainting ON"))
    if args.mode == "fps":
        print("   FPS:         {}".format(args.fps))
    print()

    if args.batch:
        if not os.path.isdir(args.input):
            print("ERROR: Not a directory: {}".format(args.input))
            sys.exit(1)
        process_batch(args.input, args.output, mode=args.mode, fps=args.fps, crop=crop, masks=masks, no_logo=args.no_logo)
    else:
        if not os.path.isfile(args.input):
            print("ERROR: File not found: {}".format(args.input))
            sys.exit(1)
        process_video(args.input, args.output, mode=args.mode, fps=args.fps, crop=crop, masks=masks, no_logo=args.no_logo)


if __name__ == "__main__":
    main()
